blueprint:
  name: Zigbee2MQTT - Nous LZ4 Zigbee Wireless Switch
  description: Automate your Nous LZ4 Zigbee Wireless Switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: Nous LZ4 Zigbee Wireless Switch
      description: Nous LZ4 Zigbee Wireless Switch to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  source_url: https://github.com/deep-soft/ha-blueprint/blob/dc4b846bc4dfa8725526606b07c051947bfc9687/blueprints/nous/nous_lz4_wireless_switch_z2m.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input "switch"
  attribute: action
action:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions: 
    - "{{ command == 'single' }}"
    sequence: !input "single_press"
  - conditions: 
    - "{{ command == 'double' }}"
    sequence: !input "double_press"
  - conditions: 
    - "{{ command == 'long' }}"
    sequence: !input "long_press"
